#theme: jekyll-theme-yat
remote-theme: "jeffreytse/jekyll-theme-yat"

translate_langs: []
banner: "/assets/images/banner.png"

header_pages:
  - index.html
  - about.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
