#theme: jekyll-theme-yat
remote_theme: "jeffreytse/jekyll-theme-yat@3c6242f"

translate_langs: []
title: jjk_charles
banner: "/assets/images/banner.png"

header_pages:
  - index.html
#  - lists.html
  - about.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
